version: '2'
services:
    web:
        build: .
        ports:
            - 5000:5000
        environment:
            APP_SETTINGS: config.DevelopmentConfig
            DATABASE_URL: postgresql://postgres:postgres@db/flaskbyexample
        volumes:
            - .:/code
        depends_on:
            - db
        networks:
            - db
            - proxy
    db:
        image: postgres:9.4
        ports:
            - 5433:5432
        volumes:
            - db-data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            PGDATA : /var/lib/postgresql/data/pgdata
        networks:
            - db
    nginx:
        image: nginx
        depends_on:
            - web
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - proxy
volumes:
    db-data:
        driver: local

networks:
    proxy:
    db:
