version: '2'
services:
    web:
        build: .
        ports:
            - 5000:5000
        environment:
            APP_SETTINGS: config.DevelopmentConfig
        volumes:
            - .:/code
        depends_on:
            - db
    db:
        image: postgres:9.4
        ports:
            - 5432:5432
        volumes_from:
            - pg_data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            PGDATA : /var/lib/postgresql/data/pgdata
    pg_data:
        image: alpine:latest
        volumes:
            - /var/lib/postgresql/data/pgdata
        command: "true"
